### ISSUE TITLE
Failure installing bitcoind-next-test on 10.9

### ISSUE THREAD

**Issue by WyseNynja** [WyseNynja/homebrew-bitcoin#9]
==> make -f makefile.osx DEPSDIR=/usr/local USE_UPNP=- USE_IPV6=1
ar: creating archive libleveldb.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libleveldb.a(env_win.o) has no symbols
rm -f libmemenv.a
ar -rs libmemenv.a helpers/memenv/memenv.o
ar: creating archive libmemenv.a

**Comment by luke-jr** [comment]
@WyseNynja I have pretty much entirely replaced next-test with my ljrF branch(es). The differences are:
* next-test tried to include everything, whereas ljrF only includes things that seem safe-and-easy or I personally consider valuable (subjective).
* next-test was always based on master, but ljrF is based on stable branches.
* next-test was released as two git tags (next and next-test), while ljrF is part of a different 3-tier hierarchy (syslibs, ljrF, and ljrP) released as (currently) 7 patch files.
* Policy changes are included in the separate ljrP branch, rather than mixed in with functional changes.
